# Generated by Django 3.0 on 2020-07-03 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Filial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cidade', models.CharField(max_length=150)),
                ('cnpj', models.CharField(max_length=18)),
                ('email', models.EmailField(max_length=254)),
                ('rua', models.CharField(max_length=150)),
                ('nro', models.CharField(max_length=10)),
                ('cep', models.CharField(max_length=10)),
                ('bairro', models.CharField(max_length=70)),
                ('complemento', models.CharField(blank=True, max_length=100)),
                ('latitude', models.CharField(max_length=20)),
                ('longitude', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Filial',
                'verbose_name_plural': 'Filiais',
                'db_table': 'cad_filial',
            },
        ),
    ]
